### ISSUE TITLE
TP600 - WebGL support in browser

### ISSUE THREAD

**Issue by thomassandberg** [WAGO/tp-firmware-sdk#10]
Trying to access a WebUI created with CDP Studio (https://cdpstudio.com) but this fails due to the WebGL support in the browser. It gives me the following message:

"While your browser seems to support WebGL, it is disabled or unavailable"

Is there a way to enable this before compiling the firmware?
I´m running FW24 on the TP600 panel

**Comment by falk-werner** [comment]
Hello @thomassandberg ,
thanks for your request and sorry for the late reply.

WebGL is disabled in TP600 devices due to very low performance. It cannot be enabled without re-compiling. To enable WebGL, you have to change line 331 of `ptxproj/local_src/webenginebrowser/browserapplication.cpp`:

```C++
defaultSettings->setAttribute(QWebEngineSettings::WebGLEnabled, true);
```

To apply the change, you need to re-compile the package `webenginebrowser`:
```bash
ptxdist clean webenginebrowser -q
ptxdist targetinstall webenginebrowser -q
```

The resulting `ipk` package is located in the directory `ptxproj/platform-vtp-ctp/packages` and can be installed via WBM.

**Comment by thomassandberg** [comment]
Thanks, will give it a go :)
